import { BadgeDefinition } from "../types/models";

export const BADGES: BadgeDefinition[] = [
  {
    id: "bronze-starter",
    title: "入门躺平奖",
    description: "累计放弃 1 条",
    threshold: 1,
    tier: "bronze",
    hidden: false,
    icon: "coffee",
  },
  {
    id: "bronze-procrastinate",
    title: "拖延起步者",
    description: "累计放弃 3 条",
    threshold: 3,
    tier: "bronze",
    hidden: false,
    icon: "anchor",
  },
  {
    id: "bronze-shelved",
    title: "计划搁置者",
    description: "累计放弃 5 条",
    threshold: 5,
    tier: "bronze",
    hidden: false,
    icon: "sun",
  },
  {
    id: "silver-lazy",
    title: "咸鱼进阶者",
    description: "累计放弃 10 条",
    threshold: 10,
    tier: "silver",
    hidden: false,
    icon: "award",
  },
  {
    id: "silver-sofa",
    title: "沙发守护者",
    description: "累计放弃 20 条",
    threshold: 20,
    tier: "silver",
    hidden: false,
    icon: "shield",
  },
  {
    id: "silver-masterpiece",
    title: "懒人代表作",
    description: "累计放弃 30 条",
    threshold: 30,
    tier: "silver",
    hidden: false,
    icon: "feather",
  },
  {
    id: "gold-master",
    title: "躺平大师",
    description: "累计放弃 50 条",
    threshold: 50,
    tier: "gold",
    hidden: false,
    icon: "star",
  },
  {
    id: "gold-saver",
    title: "省力宗师",
    description: "累计放弃 80 条",
    threshold: 80,
    tier: "gold",
    hidden: false,
    icon: "zap",
  },
  {
    id: "gold-shelved-king",
    title: "梦想搁置王",
    description: "累计放弃 120 条",
    threshold: 120,
    tier: "gold",
    hidden: false,
    icon: "aperture",
  },
  {
    id: "hidden-platinum-1",
    title: "隐秘一号",
    description: "神秘条件达成",
    threshold: 200,
    tier: "platinum",
    hidden: true,
    icon: "moon",
  },
  {
    id: "hidden-platinum-2",
    title: "隐秘二号",
    description: "神秘条件达成",
    threshold: 300,
    tier: "platinum",
    hidden: true,
    icon: "triangle",
  },
  {
    id: "hidden-diamond-1",
    title: "隐秘三号",
    description: "神秘条件达成",
    threshold: 500,
    tier: "diamond",
    hidden: true,
    icon: "hexagon",
  },
  {
    id: "hidden-diamond-2",
    title: "隐秘四号",
    description: "神秘条件达成",
    threshold: 800,
    tier: "diamond",
    hidden: true,
    icon: "layers",
  },
  {
    id: "hidden-dark-1",
    title: "隐秘五号",
    description: "神秘条件达成",
    threshold: 1200,
    tier: "dark-matter",
    hidden: true,
    icon: "cloud",
  },
  {
    id: "hidden-dark-2",
    title: "隐秘六号",
    description: "神秘条件达成",
    threshold: 2000,
    tier: "dark-matter",
    hidden: true,
    icon: "moon",
  },
];

export function getNewlyUnlockedBadges(
  unlockedIds: string[],
  totalCount: number
): BadgeDefinition[] {
  return BADGES.filter(
    (badge) => totalCount >= badge.threshold && !unlockedIds.includes(badge.id)
  );
}
